version: 0.{build}
skip_tags: true
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- git submodule update --init --recursive
- scripts\switch-to-hpcloud-sshd.bat
- scripts\make.bat
test: off
artifacts:
- path: output/*
  name: lifecycle
